name: Release

on:
  push:
    tags:
      - 'v*'  # 觸發條件：推送以 v 開頭的標籤 (如 v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Get dependencies
        run: go mod download

      - name: Build for multiple platforms
        run: |
          # 建立輸出目錄
          mkdir -p dist
          
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o dist/discord-bot-template-linux-amd64 .
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o dist/discord-bot-template-linux-arm64 .
          
          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -o dist/discord-bot-template-windows-amd64.exe .
          
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -o dist/discord-bot-template-darwin-amd64 .
          
          # macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -o dist/discord-bot-template-darwin-arm64 .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/discord-bot-template-linux-amd64
            dist/discord-bot-template-linux-arm64
            dist/discord-bot-template-windows-amd64.exe
            dist/discord-bot-template-darwin-amd64
            dist/discord-bot-template-darwin-arm64
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}