name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
      - name: Build Linux binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/discord-bot-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/discord-bot-linux-arm64 .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
      - name: Build Windows binaries
        run: |
          mkdir dist
          go build -o dist/discord-bot-windows-amd64.exe .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/*

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
      - name: Build macOS binaries
        run: |
          mkdir -p dist
          GOARCH=amd64 go build -o dist/discord-bot-darwin-amd64 .
          GOARCH=arm64 go build -o dist/discord-bot-darwin-arm64 .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Show files
        run: ls -R dist
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}